const express = require("express"); 
const router = express.Router(); 
const {getPrivateEmployeeData, getTickets, getTicket, getSatisfactions,getClient, addSatisfactions} = require("../controllers/private"); 
const {protectEmployeeData, protectClientData} = require("../middleware/auth");
router.route("/employeeData").get(protectEmployeeData,getPrivateEmployeeData); 
router.route("/data/tickets").get(protectEmployeeData,getTickets); 
router.route("/data/ticket").post(protectEmployeeData,getTicket); 
router.route("/data/satisfactions").get(protectEmployeeData,getSatisfactions); 
router.route("/data/client").post(protectEmployeeData,getClient);
router.route("/data/addSatisfaction").post(protectClientData, addSatisfactions);
module.exports = router;