insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (58, 58, 'Financial Analyst', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (75, 52, 'Web Designer II', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (13, 19, 'Professor', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (52, 1, 'Actuary', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (100, 61, 'Help Desk Operator', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (32, 57, 'Sales Associate', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (41, 74, 'Automation Specialist IV', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (68, 85, 'Administrative Assistant III', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (24, 78, 'Accounting Assistant II', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (6, 38, 'Senior Developer', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (90, 100, 'Assistant Media Planner', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (54, 34, 'Assistant Manager', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (23, 31, 'Assistant Media Planner', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (13, 97, 'Senior Financial Analyst', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (63, 72, 'Account Coordinator', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (52, 53, 'Safety Technician II', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (6, 79, 'Statistician I', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (83, 9, 'Clinical Specialist', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (72, 64, 'Project Manager', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (83, 67, 'Civil Engineer', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (43, 59, 'Programmer Analyst III', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (98, 40, 'Design Engineer', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (22, 43, 'Food Chemist', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (16, 71, 'Systems Administrator IV', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (34, 79, 'Financial Analyst', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (47, 70, 'Information Systems Manager', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (46, 34, 'Legal Assistant', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (1, 75, 'Geological Engineer', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (19, 50, 'Civil Engineer', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (65, 92, 'GIS Technical Architect', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (61, 78, 'Data Coordiator', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (100, 35, 'Help Desk Technician', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (23, 59, 'Computer Systems Analyst I', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (70, 43, 'Nurse Practicioner', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (43, 17, 'Clinical Specialist', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (69, 29, 'Account Coordinator', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (91, 43, 'Software Test Engineer II', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (38, 70, 'Database Administrator II', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (35, 82, 'Structural Analysis Engineer', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (77, 56, 'VP Accounting', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (55, 80, 'Sales Associate', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (25, 22, 'Developer III', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (21, 37, 'Environmental Specialist', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (15, 48, 'Junior Executive', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (92, 91, 'Geological Engineer', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (41, 72, 'Developer III', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (76, 69, 'Analog Circuit Design manager', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (22, 94, 'Senior Editor', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (19, 50, 'Technical Writer', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (79, 28, 'Systems Administrator II', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (94, 8, 'Structural Engineer', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (6, 66, 'Nuclear Power Engineer', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (7, 49, 'Recruiting Manager', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (58, 87, 'Senior Cost Accountant', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (55, 57, 'Structural Engineer', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (29, 45, 'Librarian', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (83, 69, 'Executive Secretary', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (11, 48, 'Research Associate', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (38, 72, 'Director of Sales', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (63, 85, 'Assistant Professor', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (3, 58, 'Paralegal', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (54, 13, 'Civil Engineer', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (74, 54, 'Director of Sales', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (81, 35, 'Compensation Analyst', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (59, 57, 'Physical Therapy Assistant', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (2, 12, 'Social Worker', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (46, 25, 'Quality Control Specialist', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (60, 92, 'Programmer Analyst IV', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (45, 22, 'Speech Pathologist', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (73, 20, 'Assistant Professor', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (40, 100, 'Internal Auditor', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (40, 40, 'Software Test Engineer I', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (40, 96, 'Engineer III', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (79, 21, 'VP Quality Control', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (86, 88, 'Accounting Assistant II', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (85, 65, 'Teacher', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (14, 61, 'Internal Auditor', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (37, 9, 'Legal Assistant', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (22, 2, 'Web Designer II', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (86, 16, 'Chemical Engineer', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (75, 98, 'Software Consultant', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (87, 33, 'Office Assistant I', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (31, 7, 'Structural Engineer', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (82, 59, 'Staff Accountant III', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (46, 13, 'Technical Writer', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (25, 80, 'Account Representative III', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (96, 96, 'Desktop Support Technician', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (27, 85, 'VP Product Management', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (32, 13, 'Account Representative II', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (18, 13, 'Web Designer III', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (44, 39, 'Financial Analyst', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (36, 81, 'Cost Accountant', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (87, 9, 'Programmer II', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (75, 63, 'Database Administrator III', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (66, 79, 'Product Engineer', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (31, 54, 'Statistician III', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (64, 100, 'Health Coach I', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (71, 64, 'Legal Assistant', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (22, 98, 'Help Desk Technician', 1);
insert into tblBusinessContact (BusinessID, ClientID, ContactJobTitle, ContactState) values (8, 88, 'Web Developer I', 1);
